### ISSUE TITLE
Can't build with rustc 1.78.0

### ISSUE THREAD

**Issue by b4shful** [rharish101/ReGreet#105]
Using toolchain version:
```
installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.68.2-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.78.0 (9b00956e5 2024-04-29)
```
I get this error when building:
```
   Compiling regreet v0.1.2 (/tmp/makepkg/greetd-regreet-git/src/regreet)
error[E0716]: temporary value dropped while borrowed
   --> src/sysutil.rs:177:18
    |
174 |             let cmd_prefix = if is_x11 {
    |                 ---------- borrow later stored here
...
177 |                 &Vec::new()
    |                  ^^^^^^^^^^ creates a temporary value which is freed while still in use
178 |             };
    |             - temporary value is freed at the end of this statement
    |
    = note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
error: could not compile `regreet` (bin "regreet") due to 1 previous error
```

I was able to fix it by `rustup update` which led to:
```
installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.68.2-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.83.0 (90b35a623 2024-11-26)
```
I don't know anything about Rust, but perhaps the latest ReGreet update requires some rustc at least greater than the 1.78.0 that I was previously on. The readme currently says 1.64.0+ so maybe the readme needs updated to reflect this?

**Comment by b4shful** [comment]
Oh yeah, just saw that 38d1854 bumps the rust version to 1.70. So I imagine that the README should be changed to say it needs 1.70+

**Comment by rharish101** [comment]
Thanks for bringing this to my notice. I've fixed the code so that it compiles with an MSRV of 1.75, as well as specified this in the README + manifest file.
